#include "utility.h"

void AddBook(Book);
void UpdateBooks();
void LoadBooks();
void printBook(Book*);
void printBookIndex();
void printBooksList();
int CompareBooks(Book,Book);
void AskRemoveBook(int);
void RemoveBook(Book);
void AskBookDetailsForAdding();
void SearchBook(char*,int);
void byName();
void byAuthor();
void byGenre();
void InputSearchBook();
void RemoveSingleBook();
void RemoveMultipleBook();
void RemoveAllBooks();